<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PerfilProcesso', 'doctrine');

/**
 * BasePerfilProcesso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $processo_id
 * @property integer $perfil_id
 * @property Perfil $Perfil
 * @property Processo $Processo
 * 
 * @method integer        getProcessoId()  Returns the current record's "processo_id" value
 * @method integer        getPerfilId()    Returns the current record's "perfil_id" value
 * @method Perfil         getPerfil()      Returns the current record's "Perfil" value
 * @method Processo       getProcesso()    Returns the current record's "Processo" value
 * @method PerfilProcesso setProcessoId()  Sets the current record's "processo_id" value
 * @method PerfilProcesso setPerfilId()    Sets the current record's "perfil_id" value
 * @method PerfilProcesso setPerfil()      Sets the current record's "Perfil" value
 * @method PerfilProcesso setProcesso()    Sets the current record's "Processo" value
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePerfilProcesso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('perfil_processo');
        $this->hasColumn('processo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));

        $this->hasOne('Processo', array(
             'local' => 'processo_id',
             'foreign' => 'id'));
    }
}