<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Usuario', 'doctrine');

/**
 * BaseUsuario
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $login
 * @property string $nome
 * @property string $email
 * @property string $cpf
 * @property date $data_nascimento
 * @property string $algoritmo
 * @property string $salt
 * @property string $senha
 * @property integer $status
 * @property timestamp $ultimo_acesso
 * @property Doctrine_Collection $Empresa
 * @property Doctrine_Collection $Perfis
 * @property Doctrine_Collection $Processos
 * @property Doctrine_Collection $UsuarioEmpresa
 * @property Doctrine_Collection $UsuarioPerfil
 * @property Doctrine_Collection $UsuarioProcesso
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getLogin()           Returns the current record's "login" value
 * @method string              getNome()            Returns the current record's "nome" value
 * @method string              getEmail()           Returns the current record's "email" value
 * @method string              getCpf()             Returns the current record's "cpf" value
 * @method date                getDataNascimento()  Returns the current record's "data_nascimento" value
 * @method string              getAlgoritmo()       Returns the current record's "algoritmo" value
 * @method string              getSalt()            Returns the current record's "salt" value
 * @method string              getSenha()           Returns the current record's "senha" value
 * @method integer             getStatus()          Returns the current record's "status" value
 * @method timestamp           getUltimoAcesso()    Returns the current record's "ultimo_acesso" value
 * @method Doctrine_Collection getEmpresa()         Returns the current record's "Empresa" collection
 * @method Doctrine_Collection getPerfis()          Returns the current record's "Perfis" collection
 * @method Doctrine_Collection getProcessos()       Returns the current record's "Processos" collection
 * @method Doctrine_Collection getUsuarioEmpresa()  Returns the current record's "UsuarioEmpresa" collection
 * @method Doctrine_Collection getUsuarioPerfil()   Returns the current record's "UsuarioPerfil" collection
 * @method Doctrine_Collection getUsuarioProcesso() Returns the current record's "UsuarioProcesso" collection
 * @method Usuario             setId()              Sets the current record's "id" value
 * @method Usuario             setLogin()           Sets the current record's "login" value
 * @method Usuario             setNome()            Sets the current record's "nome" value
 * @method Usuario             setEmail()           Sets the current record's "email" value
 * @method Usuario             setCpf()             Sets the current record's "cpf" value
 * @method Usuario             setDataNascimento()  Sets the current record's "data_nascimento" value
 * @method Usuario             setAlgoritmo()       Sets the current record's "algoritmo" value
 * @method Usuario             setSalt()            Sets the current record's "salt" value
 * @method Usuario             setSenha()           Sets the current record's "senha" value
 * @method Usuario             setStatus()          Sets the current record's "status" value
 * @method Usuario             setUltimoAcesso()    Sets the current record's "ultimo_acesso" value
 * @method Usuario             setEmpresa()         Sets the current record's "Empresa" collection
 * @method Usuario             setPerfis()          Sets the current record's "Perfis" collection
 * @method Usuario             setProcessos()       Sets the current record's "Processos" collection
 * @method Usuario             setUsuarioEmpresa()  Sets the current record's "UsuarioEmpresa" collection
 * @method Usuario             setUsuarioPerfil()   Sets the current record's "UsuarioPerfil" collection
 * @method Usuario             setUsuarioProcesso() Sets the current record's "UsuarioProcesso" collection
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuario extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario');
        $this->hasColumn('usuario_id as id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('usuario_nm_nomeacesso as login', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '128',
             ));
        $this->hasColumn('usuario_nm_nome as nome', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '255',
             ));
        $this->hasColumn('usuario_nm_email as email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'email' => true,
             'length' => '255',
             ));
        $this->hasColumn('usuario_nu_cpf as cpf', 'string', 11, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '11',
             ));
        $this->hasColumn('usuario_dt_dtnascimento as data_nascimento', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '25',
             ));
        $this->hasColumn('usuario_nm_algoritmo as algoritmo', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '128',
             ));
        $this->hasColumn('usuario_nm_salt as salt', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '128',
             ));
        $this->hasColumn('usuario_nm_senha as senha', 'string', 128, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '128',
             ));
        $this->hasColumn('usuario_nu_status as status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('usuario_ts_ultimoacesso as ultimo_acesso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empresa', array(
             'refClass' => 'UsuarioEmpresa',
             'local' => 'usuario_id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Perfil as Perfis', array(
             'refClass' => 'UsuarioPerfil',
             'local' => 'usuario_id',
             'foreign' => 'perfil_id'));

        $this->hasMany('Processo as Processos', array(
             'refClass' => 'UsuarioProcesso',
             'local' => 'usuario_id',
             'foreign' => 'processo_id'));

        $this->hasMany('UsuarioEmpresa', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('UsuarioPerfil', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));

        $this->hasMany('UsuarioProcesso', array(
             'local' => 'id',
             'foreign' => 'usuario_id'));
    }
}