<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioPerfil', 'doctrine');

/**
 * BaseUsuarioPerfil
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $perfil_id
 * @property integer $usuario_id
 * @property Usuario $Usuario
 * @property Perfil $Perfil
 * 
 * @method integer       getPerfilId()   Returns the current record's "perfil_id" value
 * @method integer       getUsuarioId()  Returns the current record's "usuario_id" value
 * @method Usuario       getUsuario()    Returns the current record's "Usuario" value
 * @method Perfil        getPerfil()     Returns the current record's "Perfil" value
 * @method UsuarioPerfil setPerfilId()   Sets the current record's "perfil_id" value
 * @method UsuarioPerfil setUsuarioId()  Sets the current record's "usuario_id" value
 * @method UsuarioPerfil setUsuario()    Sets the current record's "Usuario" value
 * @method UsuarioPerfil setPerfil()     Sets the current record's "Perfil" value
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuarioPerfil extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_perfil');
        $this->hasColumn('perfil_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasOne('Perfil', array(
             'local' => 'perfil_id',
             'foreign' => 'id'));
    }
}