<?php

/**
 * BaseUsuarioRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $usuario_id
 * @property string $remember_key
 * @property string $ip_address
 * @property Usuario $Usuario
 * 
 * @method integer            getId()           Returns the current record's "id" value
 * @method integer            getUsuarioId()    Returns the current record's "usuario_id" value
 * @method string             getRememberKey()  Returns the current record's "remember_key" value
 * @method string             getIpAddress()    Returns the current record's "ip_address" value
 * @method Usuario            getUsuario()      Returns the current record's "Usuario" value
 * @method UsuarioRememberKey setId()           Sets the current record's "id" value
 * @method UsuarioRememberKey setUsuarioId()    Sets the current record's "usuario_id" value
 * @method UsuarioRememberKey setRememberKey()  Sets the current record's "remember_key" value
 * @method UsuarioRememberKey setIpAddress()    Sets the current record's "ip_address" value
 * @method UsuarioRememberKey setUsuario()      Sets the current record's "Usuario" value
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuarioRememberKey extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('remember_key');
        $this->hasColumn('rememberkey_id as id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'length' => '4',
             ));
        $this->hasColumn('rememberkey_ds_key as remember_key', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('usuario_ip as ip_address', 'string', 50, array(
             'type' => 'string',
             'primary' => true,
             'length' => '50',
             ));

        $this->option('symfony', array(
             'form' => false,
             'filter' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}