<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('UsuarioProcesso', 'doctrine');

/**
 * BaseUsuarioProcesso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $usuario_id
 * @property integer $processo_id
 * @property Usuario $Usuario
 * @property Processo $Processo
 * 
 * @method integer         getUsuarioId()   Returns the current record's "usuario_id" value
 * @method integer         getProcessoId()  Returns the current record's "processo_id" value
 * @method Usuario         getUsuario()     Returns the current record's "Usuario" value
 * @method Processo        getProcesso()    Returns the current record's "Processo" value
 * @method UsuarioProcesso setUsuarioId()   Sets the current record's "usuario_id" value
 * @method UsuarioProcesso setProcessoId()  Sets the current record's "processo_id" value
 * @method UsuarioProcesso setUsuario()     Sets the current record's "Usuario" value
 * @method UsuarioProcesso setProcesso()    Sets the current record's "Processo" value
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseUsuarioProcesso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('usuario_processo');
        $this->hasColumn('usuario_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('processo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => false,
             'length' => '4',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Usuario', array(
             'local' => 'usuario_id',
             'foreign' => 'id'));

        $this->hasOne('Processo', array(
             'local' => 'processo_id',
             'foreign' => 'id'));
    }
}