<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Processo', 'doctrine');

/**
 * BaseProcesso
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descricao
 * @property string $rota
 * @property integer $status
 * @property Menu $Menu
 * @property Doctrine_Collection $Perfis
 * @property Doctrine_Collection $Usuarios
 * @property Doctrine_Collection $PerfilProcesso
 * @property Doctrine_Collection $UsuarioProcesso
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getDescricao()       Returns the current record's "descricao" value
 * @method string              getRota()            Returns the current record's "rota" value
 * @method integer             getStatus()          Returns the current record's "status" value
 * @method Menu                getMenu()            Returns the current record's "Menu" value
 * @method Doctrine_Collection getPerfis()          Returns the current record's "Perfis" collection
 * @method Doctrine_Collection getUsuarios()        Returns the current record's "Usuarios" collection
 * @method Doctrine_Collection getPerfilProcesso()  Returns the current record's "PerfilProcesso" collection
 * @method Doctrine_Collection getUsuarioProcesso() Returns the current record's "UsuarioProcesso" collection
 * @method Processo            setId()              Sets the current record's "id" value
 * @method Processo            setDescricao()       Sets the current record's "descricao" value
 * @method Processo            setRota()            Sets the current record's "rota" value
 * @method Processo            setStatus()          Sets the current record's "status" value
 * @method Processo            setMenu()            Sets the current record's "Menu" value
 * @method Processo            setPerfis()          Sets the current record's "Perfis" collection
 * @method Processo            setUsuarios()        Sets the current record's "Usuarios" collection
 * @method Processo            setPerfilProcesso()  Sets the current record's "PerfilProcesso" collection
 * @method Processo            setUsuarioProcesso() Sets the current record's "UsuarioProcesso" collection
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseProcesso extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('processo');
        $this->hasColumn('processo_id as id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('processo_nm_descricao as descricao', 'string', 60, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '60',
             ));
        $this->hasColumn('processo_nm_rota as rota', 'string', 40, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => ' ',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '40',
             ));
        $this->hasColumn('processo_nu_status as status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Menu', array(
             'local' => 'processo_id',
             'foreign' => 'processo_id'));

        $this->hasMany('Perfil as Perfis', array(
             'refClass' => 'PerfilProcesso',
             'local' => 'processo_id',
             'foreign' => 'perfil_id'));

        $this->hasMany('Usuario as Usuarios', array(
             'refClass' => 'UsuarioProcesso',
             'local' => 'processo_id',
             'foreign' => 'usuario_id'));

        $this->hasMany('PerfilProcesso', array(
             'local' => 'id',
             'foreign' => 'processo_id'));

        $this->hasMany('UsuarioProcesso', array(
             'local' => 'id',
             'foreign' => 'processo_id'));
    }
}