<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Menu', 'doctrine');

/**
 * BaseMenu
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $processo_id
 * @property string $descricao
 * @property integer $ordem
 * @property integer $menu_pai
 * @property integer $status
 * @property Menu $Submenu
 * @property Processo $Processo
 * @property Doctrine_Collection $Menu
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getProcessoId()  Returns the current record's "processo_id" value
 * @method string              getDescricao()   Returns the current record's "descricao" value
 * @method integer             getOrdem()       Returns the current record's "ordem" value
 * @method integer             getMenuPai()     Returns the current record's "menu_pai" value
 * @method integer             getStatus()      Returns the current record's "status" value
 * @method Menu                getSubmenu()     Returns the current record's "Submenu" value
 * @method Processo            getProcesso()    Returns the current record's "Processo" value
 * @method Doctrine_Collection getMenu()        Returns the current record's "Menu" collection
 * @method Menu                setId()          Sets the current record's "id" value
 * @method Menu                setProcessoId()  Sets the current record's "processo_id" value
 * @method Menu                setDescricao()   Sets the current record's "descricao" value
 * @method Menu                setOrdem()       Sets the current record's "ordem" value
 * @method Menu                setMenuPai()     Sets the current record's "menu_pai" value
 * @method Menu                setStatus()      Sets the current record's "status" value
 * @method Menu                setSubmenu()     Sets the current record's "Submenu" value
 * @method Menu                setProcesso()    Sets the current record's "Processo" value
 * @method Menu                setMenu()        Sets the current record's "Menu" collection
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseMenu extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('menu');
        $this->hasColumn('menu_id as id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('processo_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('menu_ds_descricao as descricao', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '20',
             ));
        $this->hasColumn('menu_nu_ordem as ordem', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
        $this->hasColumn('menu_nu_menupai as menu_pai', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => '4',
             ));
        $this->hasColumn('menu_nu_status as status', 'integer', 1, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'default' => '1',
             'notnull' => true,
             'autoincrement' => false,
             'length' => '1',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Menu as Submenu', array(
             'local' => 'menu_id',
             'foreign' => 'menu_nu_menupai'));

        $this->hasOne('Processo', array(
             'local' => 'processo_id',
             'foreign' => 'processo_id'));

        $this->hasMany('Menu', array(
             'local' => 'menu_nu_menupai',
             'foreign' => 'menu_id'));
    }
}