<?php

/**
 * UsuarioRememberKey
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    Procine
 * @subpackage model
 * @author     Marcos Regis <marcos@marcosregis.com>
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class UsuarioRememberKey extends BaseUsuarioRememberKey
{

}