# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /:sf_culture/login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /:sf_culture/logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /:sf_culture/request_password
  param: { module: sfGuardAuth, action: password }


# default rules
homepage:
  url:   /
  param: { module: home, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:sf_culture/:module
  param: { action: index }

default:
  url:   /:sf_culture/:module/:action/*
