generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfGuardUser
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_doctrine_route:   false

    config:
      fields:
#        password: { label: "Senha:" }
#        password_again: { label: "Senha (repetir):" }
        username: {label: Username }
        is_active: { label: Active }
        is_super_admin: { label: Administrator }
#        groups_list: { label: Grupos :}
#        permissions_list: { label: "Permissões:" }
#        created_at: { label: : }
        updated_at: { label: Last update }
#        last_login: { label: "Último login:" }
#        salt: { label: "Salto:" }
#        password_is_empty: { label: "vazio:" }
#        algorithm: { label: "Algorítmo:" }
      list:
        title:   User List
        display: [=username, nome, email, created_at, updated_at, last_login]

      form:
        class: sfGuardUserAdminForm
        display:
          "User Data":                   [username, password, password_again, nome, email, data_nascimento, cpf]
          "Permissions and Groups": [is_active, is_super_admin, groups_list, permissions_list]
          
      edit:
        title: "Editing User '%%username%%'"

      new:
        title: New User
        
      filter: 
        display: [username, nome, email, is_active, is_super_admin, last_login, created_at]